image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf libmotif-dev libx11-6 libx11-dev x11proto-core-dev
  script:
    - ./configure && make && make check
